[package]
name = "blogs"
version = "1.0.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "alloc",
] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.37.0", features = ["full"] }
# postgres = "0.19.7"
# grpc = "0.8.3"
redis = { version = "0.26.0", features = ["tokio-comp"] }
axum = "0.7.5"
html = "0.6.3"
minify-html = "0.15.0"
async-graphql = "7.0.6"
mlua = { version = "0.9.8", features = ["lua53", "vendored"] }
# rust-i18n = "3.0.1"
# kafka = "0.10.0"
# teloxide = "0.12.2"
# async-graphql-actix-web = "7.0.6" # 如果你需要集成到 Actix-web
# async-graphql-warp = "7.0.6" # 如果你需要集成到 Warp
# async-graphql-tide = "7.0.6" # 如果你需要集成到 Tide
async-graphql-axum = "7.0.6"
image = "0.25.2"
rusttype = "0.9.3"
log = "0.4"
pretty_env_logger = "0.5.0"
toml = "0.8.16"
chrono = "0.4.38"
protobuf = "3.5.0"
jsonwebtoken = "9.3.0"
