import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './assets/styles/app.scss'
import './assets/styles/radix-ui.css'

import React from 'react'
import { Theme } from '@radix-ui/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blogs',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}
