import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './assets/styles/app.scss'
import './assets/styles/radix-ui.css'

import React from 'react'
import DefaultLayout from '@layouts/default'
import ToTop from '@components/totop'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blogs',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <DefaultLayout>
          {children}
          <ToTop />
        </DefaultLayout>
      </body>
    </html>
  )
}
