[server]
host = "127.0.0.1"
port = 8090

[redis]
host = "0.0.0.0"
port = 6379
password = ""
database = 4

[database]
driver = "mysql"
username = "root"
password = "secret"
host = "127.0.0.1"
port = 3306
database = "awish"

[jwt]
secret = "secret"
